## Dolos
If you're looking for a reference implementation look no further than Dolos,
a browser extension which uses Grobber to embed an episode player on popular
Anime database sites.

You can find the TypeScript code over at [Dolos' GitHub repository][dolos].
Most of the code regarding Grobber can be found in the [`common/state.ts` file][dolos-state-file].

[dolos]: https://github.com/MyAnimeStream/dolos
[dolos-state-file]: https://github.com/MyAnimeStream/dolos/blob/master/src/common/state.ts