language: node_js
node_js: node
os: linux
sudo: false
cache:
  yarn: true
matrix:
  fast_finish: true
install: travis_retry yarn install --production
script: yarn test
after_success: test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash tools/deploy.sh
notifications:
  email: false
  slack: $SLACK_WEBHOOK