FORMAT: 1A
HOST: https://mas.dokkeral.com/

# Grobber
Grobber is a powerful API providing you with all the anime data you could ever need.

# Group Anime

# Group Manga
Coming soon?

# Group Misc
## Grobber Info [/dolos-info]
Get some basic information for this Grobber server.
This endpoint is used by [Dolos] to check whether the provided url is valid.

### Get Info [GET]
+ Response 200 (application/json)
    + Attributes
        + id: `grobber`
        + version: `3.0.4`

# Data Structures

## Anime (object)
+ title: `One Piece`
+ uid: `masteranime-onepiece-en`
+ language: `en`
+ dubbed: false (boolean)
+ updated: `2018-12-30T15:41:23.168227` - ISO 8601 timestamp of last update
## Episode (object)
+ embeds: `https://mp4upload.com/embed-7l251136ll9r.html` (array)
+ poster: `https://www4.mp4upload.com/i/00457/7l251136ll9r.jpg`
+ stream (Stream, nullable)
+ updated: `2018-12-30T12:00:36.256000`
## Stream (object)
+ type: `Mp4Upload`
+ url: `https://mp4upload.com/embed-wwfu2baijbw5.html`
+ links (array)
+ poster: `https://www13.mp4upload.com/i/00457/wwfu2baijbw5.jpg`
+ updated: `2018-12-30T15:41:23.183197`