FORMAT: 1A
HOST: https://mas.dokkeral.com

# Grobber
Grobber is a powerful API providing you with all the Anime and Manga
you could ever need.

**Grobber is not a meta data provider**. If that's what you're looking for,
refer to the [Kitsu API][kitsu-api].
It is an API designed to provide an easy way to fetch Anime episodes
and Manga chapters.

[kitsu-api]: https://kitsu.docs.apiary.io

# Introduction
:[](introduction/uid.apib)

# Examples
:[](examples/dolos.apib)

:[](examples/python-cli.apib)

# Group Anime
:[](anime/anime.apib)

:[](anime/episode.apib)

# Group Manga
Coming soon?

# Group Misc
:[](misc/info.apib)


:[](data-structures.apib)