FORMAT: 1A
HOST: https://mas.dokkeral.com/

# Grobber
Grobber is a powerful API providing you with all the anime data you could ever need.

# Group Anime

# Group Manga
Coming soon?

# Group Misc
:[](misc/info.apib)

:[](data-structures.apib)