version: 2.1

orbs:
  node: circleci/node@0.0.7

jobs:
  install-test-deploy:
    executor: node/node

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install --production
      - run:
          name: Testing
          command: npm test
      - run:
          name: Deploying
          command: bash tools/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - install-test-deploy:
          filters:
            branches:
              only: docs
