## Anime [/anime]
These are the endpoints you'll want to use to search for and enquire more information about Anime.

### Search Anime [GET /anime/search/{?anime}{?language}{?dubbed}{?results}]
<a name="anime-search"><a/>
Before you can actually use any of the other endpoints you need to get an Anime.
The search endpoint does exactly that.
Based on a query (i.e. the name of an Anime) it returns matching results.

Depending on the amount of results (up to `20`) you request,
this operation can take a long time. **You should seldom request search results**
and if you do you should store the details of the result(s)!

The search results are already sorted in descending order by their `certainty` attribute.

+ Parameters
    + anime (string, required, `One Piece`) ... Title of the Anime
    + language (string, optional, `en`) ... Filter for language, defaults to `en`
    + dubbed (boolean, optional, `false`) ... Filter translation type, defaults to `false`
    + results (number, optional, `3`) ... Amount of (SearchResult)s to return, defaults to `1`

+ Response 200 (application/json)
    + Attributes
        + anime (array)
            - (SearchResult)


### Get Anime using UID [GET /anime/{?uid}]
<a name="anime-using-uid"><a/>
The best way to target an anime is by using its UID. A uid (unique identifier), as its name implies,
uniquely identifies an Anime, including the language and translation type.

+ Parameters
    + uid (string, required, `a-onepiece-masteranime-en`) ... UID to look for

+ Response 200 (application/json)
    + Attributes
        + anime (Anime)


### Get Anime using Title [GET /anime/{?anime}{?language}{?dubbed}]
<a name="anime-using-title"><a/>
You can also use the Anime's title to "identify" it.
> Beware that there might be multiple Anime with the same name!
> This method doesn't uniquely identify an Anime.

+ Parameters
    + anime (string, required, `One Piece`) ... Title of the Anime
    + language (string, optional, `en`) ... Filter for language, defaults to `en`
    + dubbed (boolean, optional, `false`) ... Filter translation type, defaults to `false`

+ Response 200 (application/json)
    + Attributes
        + anime (Anime)
