## Grobber Info [/dolos-info]
Get some basic information about this Grobber server.
This endpoint is used by [Dolos](https://github.com/MyAnimeStream/dolos)
to check whether the provided url is valid.

### Get Info [GET]
+ Response 200 (application/json)
    + Attributes
        + id: `grobber`
        + version: `3.0.4`