## Grobber Info [/grobber-info]
Get some basic information about this Grobber server.

This endpoint used to be available under `/dolos-info` which is now
**deprecated**!

### Get Info [GET]
+ Response 200 (application/json)
    + Attributes
        + id: `grobber`
        + version: `3.0.26`
